site_name: (-Battlefield by liver service-)

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - mavigation.tabs.sticky



  markdown_extensions:
    - pymdownx.superfences

