site_name: (-Battlefield by liver service-)

theme:
  name: material
  Dev: index.md
  Page 1: Battlefield manual.md
  features:
    - content.code.copy
    - navigation.tabs



  markdown_extensions:
    - pymdownx.superfences

