site_name: (-Battlefield by liver service-)

theme:
  name: material
  nav:
    dev: index
    manual: Battlefield manual.md
  features:
    - content.code.copy
    - navigation.tabs



  markdown_extensions:
    - pymdownx.superfences

