site_name: (-Liver Service, Info pages-)
site_url: https://exampleName.com/



theme:
  name: material
  Dev: index.md
  Page 1: Battlefield manual.md
  features:
    - content.code.copy
    - navigation.tabs.sticky



  markdown_extensions:
    - pymdownx.superfences

