site_name: (-Liver Service, Info pages-)

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    


  markdown_extensions:
    - pymdownx.superfences

