site_name: (-Liver Service, Info pages-)
site_url: https://exampleName.com/
nav:
- Dev:
  - index.md
  - Page 1: Battlefield manual.md
  

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs.sticky



  markdown_extensions:
    - pymdownx.superfences

